### ISSUE TITLE
Code Suggestion

### ISSUE THREAD

**Issue by taooceros** [Echostorm44/FlowLauncherPluginMyIPs#1]
https://github.com/Echostorm44/FlowLauncherPluginMyIPs/blob/2cd5e3932a1a150fa556712a1c9cae144c27f863/Flow.Launcher.Plugin.FlowLauncherPluginMyIPs/Main.cs#L10

We have supported `IAsyncPlugin` rather than `IPlugin`, which supports `async` query. It would be better to use that with `async/await` instead of using `Result` for `Task`.

**Comment by Echostorm44** [comment]
I just used the VS template, it might be a good idea to update that.  I'll make the changes in my plugins, thank you for the heads up.

**Comment by taooceros** [comment]
Yeah that may be a bit old, and not everyone need async.
